package com.qugenx.springbootwebservices.ws.services.accounts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-11-27T19:50:00.094+01:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://www.qugenx.com/springbootwebservices/ws/services/Accounts/", name = "AccountService")
@XmlSeeAlso({com.qugenx.springbootwebservices.ws.gen.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AccountService {

    @WebMethod(operationName = "GetAccountDetails", action = "http://www.qugenx.com/springbootwebservices/ws/services/Accounts/GetAccountDetails")
    @WebResult(name = "AccountDetailsResponse", targetNamespace = "http://com/qugenx/springbootwebservices/ws/gen", partName = "parameters")
    public com.qugenx.springbootwebservices.ws.gen.AccountDetailsResponse getAccountDetails(

        @WebParam(partName = "parameters", name = "AccountDetailsRequest", targetNamespace = "http://com/qugenx/springbootwebservices/ws/gen")
        com.qugenx.springbootwebservices.ws.gen.AccountDetailsRequest parameters
    );
}
